### ISSUE TITLE
Can I access the dataset in the challenge now?

### ISSUE THREAD

**Issue by cookie-csooo** [abenhamadou/3DTeethSeg22_challenge#2]
I applied to join the  challenge currently, but no one reviewed it. It show that "Your request to join 3DTeethSeg, sent Mar 27, 2023 at 15:31, is awaiting review.".

**Comment by kouhou** [comment]
Same question.
“Your request to join 3DTeethSeg, sent Apr 06, 2023 at 13:37, is awaiting review.”

i konw this challenge is over, is it possible to obtain the raw data to continue the algorithm development？

jana.zhenggf@gmail.com
